# Generated by Django 2.2.14 on 2020-07-28 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('long', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=210, null=True)),
                ('country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ping_time', models.CharField(blank=True, max_length=20, null=True)),
                ('web_link', models.TextField(blank=True, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('test_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
