# Generated by Django 2.2.14 on 2020-08-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200804_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingdata',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
