# Generated by Django 2.2.14 on 2020-08-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pingdata_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='code',
            new_name='code_2',
        ),
        migrations.AddField(
            model_name='country',
            name='code_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
