# Generated by Django 2.2.14 on 2020-08-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200810_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
