# Generated by Django 2.2.14 on 2020-08-25 19:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200811_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetDataFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra', models.FloatField(blank=True, max_length=1000, null=True)),
                ('at_time', models.IntegerField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country')),
            ],
        ),
    ]
