# Generated by Django 2.2.14 on 2020-08-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_internetdataflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internetdataflow',
            old_name='intra',
            new_name='gb_per_sec',
        ),
        migrations.AlterField(
            model_name='internetdataflow',
            name='at_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
