# Generated by Django 2.2.14 on 2020-08-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200825_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFlowMatrixCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country')),
            ],
        ),
        migrations.CreateModel(
            name='DataFlowMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_gb_per_month', models.FloatField(blank=True, max_length=1000, null=True)),
                ('from_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DataFlowMatrixCountry')),
                ('to_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country')),
            ],
        ),
    ]
