# Generated by Django 2.2.14 on 2020-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_dataflowmatrix_dataflowmatrixcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
